# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"

  config.vm.provider "virtualbox"

  config.vm.network "forwarded_port", guest: 8000, host: 8080

  config.vm.provision "ansible" do |ansible|

  	ansible.verbose        = true
    ansible.playbook = "../../Ansible/Automated_Scripts/HuntEvil.yaml"
    ansible.extra_vars = {
                          RunningOn: "0.0.0.0:8000", App: "App"

                        }
  end

end
